urls.py
from django.conf.urls import url
from . import views

app_name = 'goNow'
urlpatterns = [
	#ex: /groupTracker
	url(r'^$', views.index, name='index'),
	#url(r'^(?P<group_id>[0-9]+)/$', views.details, name='details'),
	url(r'^submitSearch/$', views.submitSearch, name='submitSearch'),
	#url(r'^submit/(?P<pk>\d+)/$', views.submit, name='submit'),
	#url(r'^showAll/$', views.showAll, name='showAll'),
	#url(r'^delete/$', views.delete, name='delete'),
	#url(r'^(?P<group_id>[0-9]+)/showAll/$', views.showAll, name='showAll'),
]

models.py
from django.db import models

class UserProfile(models.Model):
    user_id = models.IntegerField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)

    def __str__(self):
        return (self.user_id + " " + self.first_name + " | " + self.last_name + " | " + self.age + " | " + self.city + ", " + self.state)


class Trip(models.Model):
    trip_id = models.IntegerField(primary_key=True)
    user_id = models.IntegerField(unique=True)
    trip_location = models.CharField(max_length=200)
    trip_budget = models.IntegerField(default=0)
    trip_start_date = models.CharField(max_length=50)
    trip_end_date = models.CharField(max_length=50)
    distance_from_you = models.IntegerField(default=0)

    def __str__(self):
        return (self.trip_id + " " + self.user_id + " | " + self.trip_location + " | " + self.trip_start_date + " | " + self.trip_end_date)

class Subscribe(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=200)
	
	def __str__(self):
		return (self.name + " | " + self.email)

#######
#trip_location = form.cleaned_data['trip_location']
#				trip_start_date = form.cleaned_data['trip_start_date']
#				trip_budget = form.cleaned_data['trip_budget']
#				distance_from_you = form.cleaned_data['distance_from_you']
#				TripSearchForm.objects.filter()

forms.py
from django import forms
from .models import UserProfile, Trip, Subscribe

class UserInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'age', 'city', 'state',)

class TripSearchForm(forms.Form):
    trip_location = forms.CharField(label='Where..',max_length=200,widget=forms.TextInput(attrs={'placeholder': 'Where..'}))
    trip_start_date = forms.DateField(label='When..',widget=forms.TextInput(attrs={'placeholder': 'When..'}))
    #trip_end_date = forms.DateField()
    trip_budget = forms.IntegerField(label='Budget..',widget=forms.TextInput(attrs={'placeholder': 'Budget..'}))
    distance_from_you = forms.IntegerField(label='Area Range..',widget=forms.TextInput(attrs={'placeholder': 'Area Range..'}))
    #class Meta:
    #    model = Trip
    #   fields = ('trip_location','trip_start_date','trip_end_date',)
    
class SubscribeForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField(max_length=200)

views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

import logging
logger = logging.getLogger(__name__)

from .forms import TripSearchForm, UserInfoForm, SubscribeForm
from .models import UserProfile, Trip, Subscribe


def index(request):
	#group = GroupInfo.objects.order_by('id')[:5]
	#context = {'group': group}
	#return render(request, 'groupTracker/index.html', context)
	if request.method == "POST":
		if 'submitSearch' in request.POST:
			form = TripSearchForm(request.POST)
			if form.is_valid():
				trip_location = form.cleaned_data['trip_location']
				trip_start_date = form.cleaned_data['trip_start_date']
				trip_budget = form.cleaned_data['trip_budget']
				distance_from_you = form.cleaned_data['distance_from_you']
				return redirect('goNow:submitSearch')
		# elif 'delete' in request.POST:
		# 	searchStr = GroupInfoDeleteForm(request.POST)
		# 	if searchStr.is_valid():
		# 		#logger.error(searchStr)
		# 		l_name = searchStr.cleaned_data['last_name']
		# 		g_name = searchStr.cleaned_data['group_name']
		# 		GroupInfo.objects.filter(last_name=l_name).filter(group_name=g_name).delete()
		# 		return redirect('groupTracker:delete')
		# elif 'find' in request.POST:
		# 	searchStr = GroupInfoFindForm(request.POST)
		# 	if searchStr.is_valid():
		# 		c_name = searchStr.cleaned_data['class_name']
		# 		records = GroupInfo.objects.filter(class_name=c_name)
		# 		return redirect('groupTracker:details', records)
		elif 'subscribe' in request.POST:
			#data = {'name':
			#}
			
			return render(request, 'goNow/subscribe.html',)
	else:
		form = TripSearchForm()
		return render(request, 'goNow/home.html', {'form':form,})

def submitSearch(request,):
	post = get_object_or_404(Trip, pk=pk)
	return render(request, 'goNow/results.html', {'post':post})

templates/goNow/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'goNow/css/creative.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'goNow/modal/modal.js' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'goNow/modal/login.modal.css' %}" />


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>goNow</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>


    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'goNow/css/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Custom CSS 
    <link rel="stylesheet" href="css/creative.css" type="text/css">-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="page-top">
    <!-- Facebook is too slow anywhere else.. -->
        <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '514319752101214',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));


   // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else if (response.status === 'not_authorized') {
      // The person is logged into Facebook, but not your app.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    } else {
      // The person is not logged into Facebook, so we're not sure if
      // they are logged into this app or not.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into Facebook.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }
// Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--------------- End  Facebook Stuff --------------------->




    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href={% url 'goNow:index' %}><img class="logo" src="{% static 'goNow/images/go-now-logo.png' %}">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <!--<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
                        </fb:login-button>
                        <div id="status">
                        </div>-->
                    </li>
                    <li>
                        <a href="#signup" class="page-scroll" role="button" data-toggle="modal" data-target="#login-modal">Sign Up</a>
                    </li>
                    <li>
                        <a href="#login" class="page-scroll" role="button" data-toggle="modal" data-target="#login-modal">Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
{% block content %}
{% endblock %}


<!-- Extras Below here -->
<!-- BEGIN # MODAL LOGIN -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    	<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header" align="center">
					<img class="img-circle" id="img_logo" src="{% static 'goNow/images/go-now-logo.png' %}">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
					</button>
				</div>
                
                <!-- Begin # DIV Form -->
                <div id="div-forms">
                
                    <!-- Begin # Login Form -->
                    <form id="login-form">
		                <div class="modal-body">
				    		<div id="div-login-msg">
                                <div id="icon-login-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-login-msg">Type your username and password.</span>
                            </div>
				    		<input id="login_username" class="form-control" type="text" placeholder="Username" required>
				    		<input id="login_password" class="form-control" type="password" placeholder="Password" required>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Remember me
                                </label>
                            </div>
        		    	</div>
				        <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
                            </div>
				    	    <div>
                                <button id="login_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
                                <button id="login_register_btn" type="button" class="btn btn-link">Register</button>
                            </div>
				        </div>
                    </form>
                    <!-- End # Login Form -->
                    
                    <!-- Begin | Lost Password Form -->
                    <form id="lost-form" style="display:none;">
    	    		    <div class="modal-body">
		    				<div id="div-lost-msg">
                                <div id="icon-lost-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-lost-msg">Type your e-mail.</span>
                            </div>
		    				<input id="lost_email" class="form-control" type="text" placeholder="E-Mail" required>
            			</div>
		    		    <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
                            </div>
                            <div>
                                <button id="lost_login_btn" type="button" class="btn btn-link">Log In</button>
                                <button id="lost_register_btn" type="button" class="btn btn-link">Register</button>
                            </div>
		    		    </div>
                    </form>
                    <!-- End | Lost Password Form -->
                    
                    <!-- Begin | Register Form -->
                    <form id="register-form" style="display:none;">
            		    <div class="modal-body">
		    				<div id="div-register-msg">
                                <div id="icon-register-msg" class="glyphicon glyphicon-chevron-right"></div>
                                <span id="text-register-msg">Register an account.</span>
                            </div>
		    				<input id="register_username" class="form-control" type="text" placeholder="Username" required>
                            <input id="register_email" class="form-control" type="text" placeholder="E-Mail" required>
                            <input id="register_password" class="form-control" type="password" placeholder="Password" required>
            			</div>
		    		    <div class="modal-footer">
                            <div>
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Register</button>
                            </div>
                            <div>
                                <button id="register_login_btn" type="button" class="btn btn-link">Log In</button>
                                <button id="register_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
                            </div>
		    		    </div>
                    </form>
                    <!-- End | Register Form -->
                    
                </div>
                <!-- End # DIV Form -->
                
			</div>
		</div>
	</div>
    <!-- END # MODAL LOGIN -->








    <!-- Plugin JavaScript -->
    <script src="{% static 'goNow/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/jquery.fittext.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>


</body>

</html>

templates/goNow/home.html
{% extends 'goNow/base.html' %}
{% load static %}
{% block content %}
<header>
    <div class="header-content">
        <div class="header-content-inner">
           <hr>
            <img class="logo-main" src="{% static 'goNow/images/go-now-logo.png' %}">
                <hr>
                    <form method="POST" class="search-form" hidden="true">{% csrf_token %}
                    <!-- Location -->
                    {{ form.trip_location }}
                    
                    <!-- When -->
                    {{ form.trip_start_date }}
                    
                    <!-- Budget -->
                    {{ form.trip_budget }}

                    <!-- Area around user. -->
                    {{ form.distance_from_you }}
                   
                     <button type="submit" name="submitSearch" class="submitSearch btn btn-default btn-xs">Search</button>
                 </form>
                 <div class="center"><button data-toggle="modal" data-target="#squarespaceModal" class="btn btn-primary center-block">Subscribe Now!</button></div>
               <!-- <a href="#about" class="btn btn-primary btn-xl page-scroll">Download</a> -->
    <section>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
               <h2 style="color:#FFFFFF;">Coming Soon...</h2>
          </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
               <img src="{% static 'goNow/images/ios.png' %}" width="130px" height="40px">
               <img src="{% static 'goNow/images/google.png' %}" width="130px" height="40px">
         </div>
     </div>
    </section>
        </div>
    </div>
</header>


<!----  MODAL ----->




<!-- line modal -->
<div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
			<h3 class="modal-title" id="lineModalLabel">Subscribe</h3>
		</div>
		<div class="modal-body">
			
            <!-- content goes here -->
			<form method="POST">{% csrf_token %}
                <div class="form-group">
                <label for="exampleInputPassword1">Name</label>
                <input type="text" class="form-control" id="exampleInputName1" placeholder="Name">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
              </div>
              <button type="submit" name="subscribe" class="btn btn-default">Submit</button>
            </form>

		</div>
	</div>
  </div>
</div>

{% endblock %}

templates/goNow/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'goNow/css/creative.css' %}" />

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>goNow</title>

    <!-- Bootstrap Core CSS 
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">-->

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Custom CSS 
    <link rel="stylesheet" href="css/creative.css" type="text/css">-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Welcome to goNow
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#portfolio">Sign Up</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#login">Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <hr>
                <h1>  &nbsp;Welcome to goNow</h1>
                <hr>
                <p>{{ form.as_p }}</p>
               <!-- <a href="#about" class="btn btn-primary btn-xl page-scroll">Download</a> -->
            </div>
            <div class="special-content">
            <img src="{% static 'goNow/images/ios.png' %}" width="130px" height="40px">
            <img src="{% static 'goNow/images/google.png' %}"width="130px" height="40px">
            </div>
        </div>
    </header>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>

templates/goNow/indexcopy.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'goNow/css/creative.css' %}" />

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>goNow</title>

    <!-- Bootstrap Core CSS 
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">-->

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Custom CSS 
    <link rel="stylesheet" href="css/creative.css" type="text/css">-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Welcome to goNow
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#portfolio">Sign Up</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#login">Login</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <hr>
                <h1>  &nbsp;Welcome to goNow</h1>
                <hr>
                <p>{{ form.as_p }}</p>
               <!-- <a href="#about" class="btn btn-primary btn-xl page-scroll">Download</a> -->
            </div>
            <div class="special-content">
            <img src="{% static 'goNow/images/ios.png' %}" width="130px" height="40px">
            <img src="{% static 'goNow/images/google.png' %}"width="130px" height="40px">
            </div>
        </div>
    </header>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>